import jsPDF from "jspdf";
import type { PaperSection } from "@/hooks/usePapers";

const journalFonts: Record<string, { titleSize: number; bodySize: number; columns: 1 | 2 }> = {
  // Journals
  ieee: { titleSize: 24, bodySize: 10, columns: 2 },
  springer: { titleSize: 20, bodySize: 11, columns: 1 },
  elsevier: { titleSize: 22, bodySize: 10, columns: 1 },
  acm: { titleSize: 22, bodySize: 9, columns: 2 },
  wiley: { titleSize: 20, bodySize: 11, columns: 1 },
  "taylor-francis": { titleSize: 20, bodySize: 11, columns: 1 },
  sage: { titleSize: 20, bodySize: 11, columns: 1 },
  mdpi: { titleSize: 18, bodySize: 10, columns: 1 },
  plos: { titleSize: 20, bodySize: 10, columns: 1 },
  nature: { titleSize: 22, bodySize: 10, columns: 1 },
  science: { titleSize: 22, bodySize: 10, columns: 1 },
  // Conferences
  "ieee-conf": { titleSize: 24, bodySize: 10, columns: 2 },
  "acm-conf": { titleSize: 22, bodySize: 9, columns: 2 },
  neurips: { titleSize: 20, bodySize: 10, columns: 1 },
  icml: { titleSize: 20, bodySize: 10, columns: 1 },
  cvpr: { titleSize: 24, bodySize: 10, columns: 2 },
  aaai: { titleSize: 24, bodySize: 10, columns: 2 },
  iclr: { titleSize: 20, bodySize: 10, columns: 1 },
  acl: { titleSize: 22, bodySize: 10, columns: 2 },
  // Standards
  scopus: { titleSize: 20, bodySize: 11, columns: 1 },
  "web-of-science": { titleSize: 20, bodySize: 11, columns: 1 },
  apa7: { titleSize: 20, bodySize: 12, columns: 1 },
  chicago: { titleSize: 20, bodySize: 12, columns: 1 },
  mla: { titleSize: 20, bodySize: 12, columns: 1 },
  harvard: { titleSize: 20, bodySize: 12, columns: 1 },
};

export function exportToPDF(sections: PaperSection[], journal: string, paperTitle: string) {
  const config = journalFonts[journal] || journalFonts.ieee;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const addPage = () => {
    doc.addPage();
    y = margin;
  };

  const checkSpace = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      addPage();
    }
  };

  // Title
  const titleSection = sections.find((s) => s.id === "title");
  if (titleSection?.content) {
    doc.setFontSize(config.titleSize);
    doc.setFont("helvetica", "bold");
    const titleLines = doc.splitTextToSize(titleSection.content, contentWidth);
    checkSpace(titleLines.length * config.titleSize * 0.5);
    doc.text(titleLines, pageWidth / 2, y, { align: "center" });
    y += titleLines.length * config.titleSize * 0.45 + 8;
  }

  // Authors placeholder
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Author(s)", pageWidth / 2, y, { align: "center" });
  y += 8;

  // Horizontal rule
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Content sections
  const contentSections = sections.filter(
    (s) => s.id !== "title" && s.content.trim()
  );

  for (const section of contentSections) {
    // Section heading
    checkSpace(15);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    const heading = section.id === "references" ? "REFERENCES" : section.label.toUpperCase();
    doc.text(heading, margin, y);
    y += 6;

    // Section body
    doc.setFontSize(config.bodySize);
    doc.setFont("times", "normal");
    const lines = doc.splitTextToSize(section.content, contentWidth);

    for (const line of lines) {
      checkSpace(5);
      doc.text(line, margin, y);
      y += config.bodySize * 0.42;
    }
    y += 6;
  }

  // Footer on each page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: "center" });
    doc.text(`Generated by PaperForge`, pageWidth - margin, pageHeight - 10, { align: "right" });
    doc.setTextColor(0);
  }

  const filename = (paperTitle || "research-paper").replace(/[^a-zA-Z0-9\s]/g, "").replace(/\s+/g, "-").toLowerCase();
  doc.save(`${filename}.pdf`);
}

export function exportToText(sections: PaperSection[], paperTitle: string) {
  const text = sections
    .filter((s) => s.content.trim())
    .map((s) => `\n${"=".repeat(60)}\n${s.label.toUpperCase()}\n${"=".repeat(60)}\n\n${s.content}`)
    .join("\n\n");

  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const filename = (paperTitle || "research-paper").replace(/[^a-zA-Z0-9\s]/g, "").replace(/\s+/g, "-").toLowerCase();
  a.download = `${filename}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportToLaTeX(sections: PaperSection[], journal: string, paperTitle: string) {
  const title = sections.find((s) => s.id === "title")?.content || "Untitled";
  const abstract = sections.find((s) => s.id === "abstract")?.content || "";
  const keywords = sections.find((s) => s.id === "keywords")?.content || "";

  const docClass = journal === "ieee" ? "IEEEtran" : "article";
  const contentSections = sections.filter((s) => !["title", "abstract", "keywords"].includes(s.id) && s.content.trim());

  let latex = `\\documentclass{${docClass}}
\\usepackage[utf8]{inputenc}
\\usepackage{graphicx}
\\usepackage{hyperref}
\\usepackage{amsmath}

\\title{${escapeLatex(title)}}
\\author{Author Name}
\\date{\\today}

\\begin{document}
\\maketitle

\\begin{abstract}
${escapeLatex(abstract)}
\\end{abstract}

\\textbf{Keywords:} ${escapeLatex(keywords)}

`;

  for (const section of contentSections) {
    const sectionName = section.label;
    latex += `\\section{${escapeLatex(sectionName)}}\n${escapeLatex(section.content)}\n\n`;
  }

  latex += `\\end{document}\n`;

  const blob = new Blob([latex], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const filename = (paperTitle || "research-paper").replace(/[^a-zA-Z0-9\s]/g, "").replace(/\s+/g, "-").toLowerCase();
  a.download = `${filename}.tex`;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeLatex(text: string): string {
  return text
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/[&%$#_{}]/g, (m) => `\\${m}`)
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}
